id: PA11B21AC
initial_creation_type: input
source_metadata:
  title: Sickness and Healing
  language: de
  description: 'Lotsawa House presents the following texts as part of our Sickness
    and Healing Series:'
  volume:
    7b29f59fbd994dda882fe8f2c7835c39:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    e351017f9ae14dad97db93f600438e42:
      title: How to Transform Sickness and Other Circumstances
      parent: Advice
    9de04a1190d847e9aff69cd6f60cb792:
      title: The Universal Medicine for Healing All Ills
      parent: Advice
    081bdd2127ad48d3bed3bb2f729cd09e:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    09d66488cce44fa6b67a144790945c0a:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    dd8e1948f5c04b539335380b499fbc99:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Practices
    d62a6e6282244ce98d620a94abc25dfe:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Practices
    ba375efb3b4d4fe3b0d499cce0d108ec:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Practices
    934790cad08c49818385862ef2dccb9f:
      title: Daily Practice of Dorje Gotrab
      parent: Practices
    4a00a149591047f7b023dff250b2aac2:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Practices
    215e227d51574636b3f9a1f9ed5a44ab:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Practices
    ae2d0800037546e2ad5bfe02d07fc07b:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    72271c7bd36349dc9623c5bc32b62b23:
      title: Acala Sādhana
      parent: Practices
    0cc023baf8c74121a1b4601a16e53ec3:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Practices
    bc9892f2a2b0419484089d66c4b1f629:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
created_at: '2022-03-01T05:47:13.659495'
last_modified_at: '2022-03-01T05:47:13.659498'
